function anfisintf(action)
% This is the machine-generated representation of a MATLAB object
% and its children.  Note that handle values may change when these
% objects are re-created. This may cause problems with some callbacks.
% The command syntax may be supported in the future, but is currently 
% incomplete and subject to change.
%
% To re-open this system, just type the name of the m-file at the MATLAB
% prompt. The M-file and its associtated MAT-file must be on your path.

% Copyright (c) 1994-98 by The MathWorks, Inc.
% $Revision: 1.2 $

if strcmp(action, 'init')
load anfisintf                         

a = figure('Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'Position',[498 339 560 420], ...
	'Tag','Fig1');
b = axes('Parent',a, ...
	'Box','on', ...
	'ButtonDownFcn','ctlpanel RbBox', ...
	'CameraUpVector',[0 1 0], ...
	'CameraUpVectorMode','manual', ...
	'Color','none', ...
	'ColorOrder',mat1, ...
	'HandleVisibility','callback', ...
	'Position',[-0.00535714 -0.0047619 1 1], ...
	'Tag','GuideSelectionAxes', ...
	'XColor',[1 1 1], ...
	'XGrid','on', ...
	'XTickLabelMode','manual', ...
	'YColor',[1 1 1], ...
	'YGrid','on', ...
	'YTickLabelMode','manual', ...
	'ZColor',[0 0 0], ...
	'ZGrid','on', ...
	'ZTickLabelMode','manual');
c = text('Parent',b, ...
	'Color',[1 1 1], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[0.499104 -0.0202864 0], ...
	'Tag','Text5', ...
	'VerticalAlignment','cap');
set(get(c,'Parent'),'XLabel',c);
c = text('Parent',b, ...
	'Color',[1 1 1], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[-0.0170251 0.5 0], ...
	'Rotation',90, ...
	'Tag','Text6', ...
	'VerticalAlignment','baseline');
set(get(c,'Parent'),'YLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','right', ...
	'Position',[0.00268817 1.00358 0], ...
	'Tag','Text7', ...
	'Visible','off');
set(get(c,'Parent'),'ZLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[0.499104 1.0179 0], ...
	'Tag','Text8', ...
	'VerticalAlignment','bottom');
set(get(c,'Parent'),'Title',c);
b = uicontrol('Parent',a, ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'ButtonDownFcn','plot(peaks(10))', ...
	'Callback','anfisintf('''start''')', ...
	'Position',[445 352 83 34], ...
	'String','Start', ...
	'Tag','StartBtn');
b = axes('Parent',a, ...
	'CameraUpVector',[0 1 0], ...
	'CameraUpVectorMode','manual', ...
	'Color',[1 1 1], ...
	'ColorOrder',mat2, ...
	'Position',[0.108929 0.447619 0.503571 0.488095], ...
	'Tag','Axes1', ...
	'XColor',[0 0 0], ...
	'YColor',[0 0 0], ...
	'ZColor',[0 0 0]);
c = line('Parent',b, ...
	'Color',[0 0 1], ...
	'Tag','Line1', ...
	'XData',mat3, ...
	'YData',mat4);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[20 0.00426471 0], ...
	'Tag','Text1', ...
	'VerticalAlignment','cap');
set(get(c,'Parent'),'XLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[-4.76868 0.0401471 0], ...
	'Rotation',90, ...
	'Tag','Text2', ...
	'VerticalAlignment','baseline');
set(get(c,'Parent'),'YLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','right', ...
	'Position',[-8.75445 0.0780882 0], ...
	'Tag','Text3', ...
	'Visible','off');
set(get(c,'Parent'),'ZLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[20 0.0722059 0], ...
	'Tag','Text4', ...
	'VerticalAlignment','bottom');
set(get(c,'Parent'),'Title',c);
b = uicontrol('Parent',a, ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','anfiscb', ...
	'Position',[448 303 78 31], ...
	'String','Stop', ...
	'Tag','StopBtn');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Position',[359.2 184.8 59.2 20], ...
	'Style','edit', ...
	'Tag','EditTxEpch');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'Position',[359.2 204.8 58.4 20.8], ...
	'String','Epchos:', ...
	'Style','text', ...
	'Tag','StaticText1');
b = uicontrol('Parent',a, ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'ButtonDownFcn',mat5, ...
	'Callback','anfiscb', ...
	'Position',[439 108 114 37], ...
	'String','Load Sample Data', ...
	'Tag','StopBtn');
b = uicontrol('Parent',a, ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'Callback','anfiscb', ...
	'Position',[437 52 114 36], ...
	'String','Load Testing Data', ...
	'Tag','StopBtn');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Position',[356 132.8 59.2 20.8], ...
	'Style','edit', ...
	'Tag','EditTxErr');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'Position',[356.8 156 58.4 20.8], ...
	'String','Err:', ...
	'Style','text', ...
	'Tag','StaticText1');
elseif strcmp('loadtrn')
 [fname, fpath]=uigetfile;
 disp(fname)
 disp(fpath)
end
